name: voices_for_christ
description: A mobile app for listening to messages on VoicesForChrist

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #audioplayers: ^0.17.0
  #audio_service: 0.17.0-nullsafety.0
  audio_service:
    git: 
      url: https://github.com/ryanheise/audio_service.git
      ref: 9c1dfc4
  audio_session: ^0.1.0
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.0
  dio: ^4.0.0
  #flutter_downloader: ^1.5.2
  #flutter_local_notifications: ^4.0.1
  fluttertoast: ^8.0.6
  google_fonts: ^2.0.0
  #html: ^0.14.0+4
  http: ^0.13.0
  just_audio: ^0.7.2
  path: ^1.7.0
  path_provider: ^2.0.1
  #percent_indicator: ^2.1.9+1
  #phone_state_i: ^0.0.3
  scoped_model: ^1.1.0
  shared_preferences: ^2.0.4
  sliding_up_panel: ^1.0.2
  sqflite: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/initial_message_database.db

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
